# Generated by Django 4.2.13 on 2024-06-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('service_name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Название сервиса')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль сервиса')),
            ],
        ),
    ]
