# Generated by Django 4.2.13 on 2024-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, unique=True, verbose_name='Название сервиса')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль сервиса')),
            ],
        ),
    ]
