# Generated by Django 4.2.13 on 2024-06-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='password',
            name='service_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название сервиса'),
        ),
    ]
